import os

PORT = os.environ.get("PORT", 3001)
ENDPOINT_MASTER_DETAIL = "/api/masterdetail"
COSMOS_DATABASE = "List"
COSMOS_CONTAINER = "ListItems"
ENDPOINT_LIST = "/api/list"
ENDPOINT_GRID = "/api/grid"

HTTP_STATUS_404_NOT_FOUND = 404
HTTP_STATUS_201_CREATED = 201
HTTP_STATUS_500_INTERNAL_SERVER_ERROR = 500
